# Generated by Django 4.2.5 on 2023-09-14 19:37

from django.db import migrations, models
import shortener.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Url",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("long_url", models.URLField()),
                (
                    "short_url",
                    models.CharField(
                        default=shortener.models.generate_short_url,
                        max_length=15,
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
